[package]
name = "vision-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
vision-derive-internal = { path = "../vision-derive-internal" }
beacon_dao-allocator = { git = "ssh://git@github.com/Vision-DAO/beacon-dao.git" }
