[package]
name = "vision-derive-test"
version = "0.1.0"
edition = "2021"

[dependencies]
vision-derive = { path = "../" }
vision-utils = { path = "../../" }
wasm-bindgen = "0.2"
serde = "1.0.145"
serde_json = "1.0.86"
wasmer = "2.3.0"